Add COAUTHORS_PATH to shell script

diff --git a/git-coauthor b/git-coauthor
--- a/git-coauthor
+++ b/git-coauthor
@@ -12,7 +12,6 @@ fi
 message_parts=()
 co_authors=()
 
-
 while [ $# -gt 0 ]
 do
     case "$1" in
@@ -46,14 +45,32 @@ then
     help
 fi
 
+COAUTHORS_FILE=~/.gitauthors
+if [ -n "$COAUTHORS_PATH" ]; then
+    COAUTHORS_FILE=$COAUTHORS_PATH
+fi
+
+if [ ! -e $COAUTHORS_FILE ]; then
+    printf "\033[1;33mError:\033[0m $COAUTHORS_FILE not found.\n"
+    exit 1
+fi
+if [ ! -f $COAUTHORS_FILE ]; then
+    printf "\033[1;33mError:\033[0m $COAUTHORS_FILE is not a file.\n"
+    exit 1
+fi
+if [ ! -r $COAUTHORS_FILE ]; then
+    printf "\033[1;33mError:\033[0m $COAUTHORS_FILE is not readable.\n"
+    exit 1
+fi
+
 for co_author in $co_authors
 do
-    lines=`grep = <(grep -A2 "\[$co_author\]" ~/.gitauthors) | sed -e 's/ *= */=/g' -e 's/^ *//' -e 's/ *$//'`
+    lines=`grep = <(grep -A2 "\[$co_author\]" $COAUTHORS_FILE) | sed -e 's/ *= */=/g' -e 's/^ *//' -e 's/ *$//'`
     name=`echo "$lines" | grep -o 'name=.*$' | cut -d '=' -f 2`
     email=`echo "$lines" | grep -o 'email=.*$' | cut -d '=' -f 2`
     if [ -z "$name" ] || [ -z "$email" ]
     then
-        printf "\033[1;33mWarning:\033[0m $co_author not found in ~/.gitauthors. Skipping.\n"
+        printf "\033[1;33mWarning:\033[0m $co_author not found in $COAUTHORS_FILE. Skipping.\n"
         continue
     fi
     message_parts+=("-m" "\"Co-authored-by: $name <$email>\"")
